# Generated by Django 5.1.1 on 2024-10-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_category_alter_product_slug_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
