# Generated by Django 5.1.1 on 2024-12-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
