# Generated by Django 5.1.1 on 2024-12-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_remove_fileuploudmodel_image_fileuploudmodel_iimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileuploudmodel',
            old_name='iimage',
            new_name='image',
        ),
    ]
